FROM nginx:stable-alpine
# Copy custom nginx.conf to container
COPY nginx.conf /etc/nginx/nginx.conf
# (optionally) copy any static SSL certs, conf.d files etc.
# COPY certs/ /etc/letsencrypt/live/yourdomain/